server:
  port: 8081
spring:
  #  mail:
  #    # 配置 SMTP 服务器地址
  #    host: smtp.qq.com
  #    # 发送者邮箱
  #    username: 252127196@qq.com
  #    # 配置密码，注意不是真正的密码，而是刚刚申请到的授权码
  #    password: swmecvmlqcprbjfd
  #    # 端口号465或587
  #    port: 587
  #    # 默认的邮件编码为UTF-8
  #    default-encoding: UTF-8
  #    # 配置SSL 加密工厂
  #    properties:
  #      mail:
  #        smtp:
  #          socketFactoryClass: javax.net.ssl.SSLSocketFactory
  #        #表示开启 DEBUG 模式，这样，邮件发送过程的日志会在控制台打印出来，方便排查错误
  #        debug: true
  datasource:
    url: jdbc:mysql://rm-wz963ju312wgv19502o.mysql.rds.aliyuncs.com:3306/mozi
    username: mozi_root
    password: Cd40k1SKIXBQ
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package:
